#!/usr/bin/env python3
import subprocess
import os
import sys

# HARDCODED - Edit these values
HOST = '100.1.1.1'
PORT = 37422
USER = 'c_X_logs'
PASS = 'your_password_here'
DIR = '/shared_Xlogs'

# Get filename from Cribl
FILENAME = os.getenv('CRIBL_COLLECT_ARG')

# SFTP commands
sftp_commands = f"""get {DIR}/{FILENAME} -
bye
"""

# Run SFTP
result = subprocess.run(
    ['sshpass', '-p', PASS, 'sftp',
     f'-oPort={PORT}',
     '-oStrictHostKeyChecking=no',
     '-oBatchMode=no',
     f'{USER}@{HOST}'],
    input=sftp_commands,
    capture_output=True,
    text=False
)

# Output file contents to stdout
sys.stdout.buffer.write(result.stdout)
