#!/usr/bin/env python3
import paramiko
import os
import sys

# HARDCODED - Edit these values
HOST = '100.1.1.1'
PORT = 37422
USER = 'c_X_logs'
PASS = 'your_password_here'
DIR = '/shared_Xlogs'

# Get the filename Cribl gives us
FILENAME = os.getenv('CRIBL_COLLECT_ARG')

try:
    # Connect
    transport = paramiko.Transport((HOST, PORT))
    transport.connect(username=USER, password=PASS)
    sftp = paramiko.SFTPClient.from_transport(transport)
    
    # Download file and output contents
    remote_path = f"{DIR}/{FILENAME}"
    with sftp.open(remote_path, 'r') as f:
        sys.stdout.buffer.write(f.read())
    
    # Close
    sftp.close()
    transport.close()
    
except Exception as e:
    sys.stderr.write(f"Error: {e}\n")
    sys.exit(1)
